In [1]:
import pandas as pd
import numpy as np

In [7]:
sal = []
for _ in range(100):
    sal.append(np.random.randint(10000, 25000))

In [9]:
sal

[18985,
 11122,
 11085,
 12192,
 10121,
 11538,
 15009,
 24445,
 10339,
 11556,
 13688,
 22182,
 14383,
 12196,
 24822,
 17529,
 15138,
 10224,
 19717,
 22480,
 24655,
 21549,
 24616,
 21729,
 24783,
 20191,
 13241,
 12273,
 22803,
 24950,
 16155,
 11914,
 18907,
 14999,
 11476,
 12998,
 13934,
 14581,
 20955,
 14718,
 10731,
 17783,
 19581,
 19579,
 10011,
 20243,
 19447,
 17612,
 24377,
 19177,
 22357,
 19395,
 13444,
 14725,
 10581,
 12974,
 14447,
 10925,
 13378,
 19539,
 23797,
 14226,
 22503,
 14459,
 10477,
 11816,
 15729,
 21942,
 13449,
 14807,
 11626,
 24296,
 14851,
 16753,
 17100,
 12769,
 18369,
 15127,
 16175,
 23257,
 12328,
 15032,
 10402,
 14089,
 17903,
 14420,
 22608,
 13629,
 23274,
 21695,
 16082,
 17069,
 23251,
 21624,
 12678,
 22983,
 11456,
 17252,
 22084,
 12602]

In [11]:
sal[23] = 48000
sal[81] = 36800

In [13]:
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
plt.boxplot(sal);

In [17]:
sns.boxplot(sal);

In [19]:
pd.Series(sal).plot.box()

<Axes: >

#### Z-Score

In [22]:
num = np.array([1,2,2,3,3,3,4,4,4,4,5,5,5,5,5,6,6,6,6,7,7,7,8,8,9])

In [24]:
def zscore(n):
    z = (n - n.mean())/n.std()
    return z

In [26]:
zscore(num)

array([-2. , -1.5, -1.5, -1. , -1. , -1. , -0.5, -0.5, -0.5, -0.5,  0. ,
        0. ,  0. ,  0. ,  0. ,  0.5,  0.5,  0.5,  0.5,  1. ,  1. ,  1. ,
        1.5,  1.5,  2. ])

In [28]:
zscore(np.array(sal))

array([ 2.97951872e-01, -1.04857523e+00, -1.05491142e+00, -8.65339312e-01,
       -1.21999499e+00, -9.77335843e-01, -3.82932236e-01,  1.23296878e+00,
       -1.18266282e+00, -9.74253369e-01, -6.09151529e-01,  8.45433384e-01,
       -4.90133809e-01, -8.64654318e-01,  1.29752947e+00,  4.86140293e-02,
       -3.60841178e-01, -1.20235640e+00,  4.23305787e-01,  8.96465443e-01,
        1.26893097e+00,  7.37033072e-01,  1.26225228e+00,  5.26672762e+00,
        1.29085078e+00,  5.04477585e-01, -6.85699616e-01, -8.51468182e-01,
        9.51778714e-01,  1.31944928e+00, -1.86681435e-01, -9.12946400e-01,
        2.84594487e-01, -3.84644722e-01, -9.87953251e-01, -7.27313006e-01,
       -5.67024393e-01, -4.56226602e-01,  6.35311452e-01, -4.32765555e-01,
       -1.11553340e+00,  9.21111529e-02,  4.00015989e-01,  3.99673491e-01,
       -1.23883233e+00,  5.13382508e-01,  3.77068687e-01,  6.28276563e-02,
        1.22132388e+00,  3.30831587e-01,  8.75401875e-01,  3.68163764e-01,
       -6.50936167e-01, -

In [30]:
sal =  np.array(sal)

In [32]:
sal = sal[zscore(sal)<3.0]

In [34]:
len(sal)

98

In [40]:
sal = sal[zscore(sal)< -3.0]

In [42]:
len(sal)

0

#### Quartiles

In [45]:
num = np.array([56, 57, 66,45,77,87,65,12,42,23,54,44])

In [47]:
np.percentile(num, 25), np.percentile(num, 50), np.percentile(num, 75)

(43.5, 55.0, 65.25)

#### Turkey Fences

In [50]:
sal = []
for _ in range(100):
    sal.append(np.random.randint(10000, 25000))

sal[23] = 48000
sal[81] = 36800

sal = np.array(sal)

In [52]:
sal

array([18353, 22776, 15710, 12371, 22739, 22598, 18262, 14565, 21566,
       15706, 22929, 11042, 19527, 16709, 21135, 22672, 11283, 13978,
       20667, 19171, 22856, 11779, 17986, 48000, 15891, 10193, 22544,
       20288, 21874, 18895, 21143, 13151, 19637, 11189, 16317, 12595,
       23733, 19272, 17756, 11523, 13926, 19201, 18110, 24187, 15740,
       15571, 14722, 24524, 10587, 21801, 20082, 12687, 20205, 20920,
       21662, 20500, 23759, 23190, 11767, 12944, 19259, 22374, 23616,
       11676, 10979, 16513, 13341, 20980, 14500, 11476, 12624, 14241,
       18114, 22103, 14957, 23128, 24433, 10202, 24313, 16024, 11035,
       36800, 20960, 18067, 14759, 10803, 24120, 20333, 19811, 22963,
       15277, 11239, 19136, 19870, 18294, 16177, 10251, 20678, 21024,
       17729])

In [54]:
Q1 = np.percentile(sal, 25)
Q3 = np.percentile(sal, 75)

IQR = Q3 - Q1

upper_fence = Q3 + 1.5 * IQR
lower_fence = Q1 - 1.5 * IQR

In [56]:
sal > upper_fence

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [64]:
sal < lower_fence

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [68]:
sal[sal > upper_fence]

array([48000, 36800])

In [70]:
lower_fence, upper_fence

(3053.125, 32712.125)